---
<% chef_versions = %w( 13 14 ) %>
<% platforms = %w( centos-6 centos-7 ) %>

driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero
  log_level: <%= ENV['TK_CHEF_LOG_LEVEL'] || 'info' %>

platforms:
<% platforms.each do |p| %>
<%   chef_versions.each do |chef_version| %>
  - name: <%= p %>-chef-<%= chef_version %>
    driver:
      linked_clone: true
    driver_config:
      box: bento/<%= p %>
      require_chef_omnibus: <%= chef_version %>
<%   end %>
<% end %>

suites:
  - name: default
    run_list:
      - recipe[cq-unix-toolkit::default]
